### ISSUE TITLE
Pesquisar Arquitetura de pastas

### ISSUE THREAD

**Issue by LeonardoReis86** [LeonardoReis86/Includify#22]

**Comment by LeonardoReis86** [comment]
Proposta de arquitetura de pastas:

ECOnomia/
│
├── index.html          # Página inicial
│
├── css (Pasta)
│   ├── global.css      # Arquivo CSS principal
│   └── responsive.css  # Folha de estilo específica para regras responsivas
│
├── js/
│   ├── main.js         # Script JavaScript principal
│   └── utils.js        # Scripts auxiliares ou utilitários, se necessário
── assets/             # Pasta para armazenar ícones, imagens, fonts, ...
│   ├── img/
│   │   ├── logo.png
│   │   └── icons/      # Subpasta para ícones
│   │       ├── icon1.png
│   │       └── icon2.png
│   │
│   └── fonts/
│       ├── font1
│       └── font2
├── pages/              # Pasta para as outras páginas HTML do site
│    ├── about.html      # Exemplo de uma página 'Sobre'
         ├── page3.html 
         ├── page4.html 
          ├── page5.html 
│
└── docs/
    └── README.md

**Comment by 0ArS0** [comment]
Estruturas de pastas inicial no vscode:

![Image](https://github.com/user-attachments/assets/1c3bf5ce-71c0-484d-87be-7a7198cd6de8)
