### ISSUE TITLE
Criar estrutura HTML tela serviços

### ISSUE THREAD

**Issue by LeonardoReis86** [LeonardoReis86/Includify#29]

**Comment by 0ArS0** [comment]
Adicionando header e seção de busca na tela de serviços
Implementando footer e escondendo alguns elementos do aria

**Comment by 0ArS0** [comment]
Adicionando textos invisiveis para leitores de tela, modificando algumas tags com tags semanticas e reorganizando o código

**Comment by 0ArS0** [comment]
Implementei a sidebar de filtros de busca na tela de serviços
