### ISSUE TITLE
Criar Readme

### ISSUE THREAD

**Issue by 0ArS0** [LeonardoReis86/Includify#5]
- Criar um README abrangente e informativo que ajude desenvolvedores e usuários a entenderem, configurarem e contribuírem para o projeto de maneira eficaz.

**Comment by 0ArS0** [comment]
### **Telas Adicionadas**: 

- Tela de LogIn/Registro:
Formulário de LogIn e registro para usuários.

- Tela Inicial: 
Introdução da ideia do site e suas funcionalidades principais

- Tela de Listagem de Perfis:
Barra de pesquisa por nome, estado, cidade 
Lista completa paginada de perfis com destaques 
Filtros adicionais
Ranking?
 
- Tela de Detalhes do Perfil: 
Informações completas do perfil
Listagem de seus respectivos serviços
Informações para contato
Avaliação do perfil

- Tela de Detalhes de Serviços/Produtos:
Informações completos do serviço ou produto que estará vinculado a um perfil

- Tela de Adição de Serviços/Produtos:
Formulário para criação de serviços/produtos

- Tela de Criação de Perfil: 
Formulário para criação de perfis.

### **Componentes Adicionados**:
- Header
- Footer

**Comment by LeonardoReis86** [comment]
Adicionado primeira versão do readme do projeto.

**Comment by LeonardoReis86** [comment]
Atualizado divisão de entregas das sprints e incluído breve descrição do projeto.
