### ISSUE TITLE
Pesquisar Elementos para a Home

### ISSUE THREAD

**Issue by 0ArS0** [LeonardoReis86/Includify#8]
- Explorar exemplos de homepages e identificar elementos de design e interface que se alinhem com os objetivos do projeto. Isso pode incluir cabeçalhos, banners, chamadas para ação, ícones, seções de conteúdo, e rodapés.
- Criar: Com base na pesquisa, desenvolver os elementos visuais para a homepage.

**Comment by LeonardoReis86** [comment]
Pesquisado e Disponibilizado modelo de Style Guide para apreciação dos colaboradores do projeto.

https://www.figma.com/design/RmIEB4lbqqHZ3zPhhKWjlF/Dark-Style-Guide-%26-Component-Library---Freebie_v_D_2.0-(Community)?node-id=0-1&t=WPAe7wVGJiccchIb-0

**Comment by LeonardoReis86** [comment]
Proposta de modelos, ícones, perfis, apresentaçào de página para auxiliar nas reuniões de criação de telas.
https://www.figma.com/design/EegVI2MgAf3bUsOKUvngZ6/UX-Flowchart-Cards-(Community)?node-id=0-1&t=Aoxsh5hN9vPMGpHq-0

**Comment by LeonardoReis86** [comment]
Proposta tela login criada no figma concluída.
