### ISSUE TITLE
Definir regra de negócio

### ISSUE THREAD

**Issue by LeonardoReis86** [LeonardoReis86/Includify#9]
- Reunir a equipe para discutir e definir as regras de negócio que guiarão o desenvolvimento do projeto;

- Garantir que todos os membros da equipe compreendam e estejam alinhados com as diretrizes estabelecidas do projeto.

**Comment by VaniJunqueira2023** [comment]
Vou começar a fazer a regra de negócio.

**Comment by VaniJunqueira2023** [comment]
Documento inicial de quando nasceu a idea: https://docs.google.com/document/d/1VTEQXCQYwnGrQhV83X2191ixrrZk1lxPPRq6UcYrAWA/edit

**Comment by VaniJunqueira2023** [comment]
Esse é o esqueleto da regra de negócio, criei duas opções, vejam se faz sentido e se está de acordo com a proposta.

https://docs.google.com/document/d/1bbWExjKYIqsJtL4fl_OrNwal15c9BlFJzarzVFN4LZw/edit#heading=h.cu1leupp05yf

**Comment by VaniJunqueira2023** [comment]
Apresentação Canva https://www.canva.com/design/DAGNJG-0UPI/3c0rLIj6k1W4sYvEqKyKMw/edit?utm_content=DAGNJG-0UPI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by VaniJunqueira2023** [comment]
Perfil do empreendedor PCD

https://docs.google.com/document/d/1upW2Qu--q_6ADf9zKrM__-hBGso9VyC74jh06rvhcvE/edit

**Comment by VaniJunqueira2023** [comment]
Grupo 03 - InclusiWork  - Regra de negócio 05/08/2024   https://docs.google.com/document/d/1gpIQrOMIptkj9DU6MZhKIoI5kGDbKDYkNPfm7vQMjIQ/edit


Plano estratégico  https://www.canva.com/design/DAGNRitX8UA/a4SUH1VoUs91Hjd7s1TZlQ/edit

**Comment by VaniJunqueira2023** [comment]
[Documento de Requisitos
de Negócios (BRD)](https://www.canva.com/design/DAGNRitX8UA/a4SUH1VoUs91Hjd7s1TZlQ/edit)
[Apresentação Canva](https://www.canva.com/design/DAGNJG-0UPI/3c0rLIj6k1W4sYvEqKyKMw/edit?utm_content=DAGNJG-0UPI&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
